//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 13/10/2011 16:52:54
namespace SilverlightApplication6.ProxyDados
{
    
    /// <summary>
    /// There are no comments for CURSOEntities in the schema.
    /// </summary>
    public partial class CURSOEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new CURSOEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CURSOEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("CURSOModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("SilverlightApplication6.ProxyDados", typeName.Substring(10)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("SilverlightApplication6.ProxyDados", global::System.StringComparison.Ordinal))
            {
                return string.Concat("CURSOModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for TB_DESENVOLVEDOR in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TB_DESENVOLVEDOR> TB_DESENVOLVEDOR
        {
            get
            {
                if ((this._TB_DESENVOLVEDOR == null))
                {
                    this._TB_DESENVOLVEDOR = base.CreateQuery<TB_DESENVOLVEDOR>("TB_DESENVOLVEDOR");
                }
                return this._TB_DESENVOLVEDOR;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TB_DESENVOLVEDOR> _TB_DESENVOLVEDOR;
        /// <summary>
        /// There are no comments for TB_LINGUAGEM in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TB_LINGUAGEM> TB_LINGUAGEM
        {
            get
            {
                if ((this._TB_LINGUAGEM == null))
                {
                    this._TB_LINGUAGEM = base.CreateQuery<TB_LINGUAGEM>("TB_LINGUAGEM");
                }
                return this._TB_LINGUAGEM;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TB_LINGUAGEM> _TB_LINGUAGEM;
        /// <summary>
        /// There are no comments for TB_DESENVOLVEDOR in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTB_DESENVOLVEDOR(TB_DESENVOLVEDOR tB_DESENVOLVEDOR)
        {
            base.AddObject("TB_DESENVOLVEDOR", tB_DESENVOLVEDOR);
        }
        /// <summary>
        /// There are no comments for TB_LINGUAGEM in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTB_LINGUAGEM(TB_LINGUAGEM tB_LINGUAGEM)
        {
            base.AddObject("TB_LINGUAGEM", tB_LINGUAGEM);
        }
    }
    /// <summary>
    /// There are no comments for CURSOModel.TB_DESENVOLVEDOR in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID_DESENVOLVEDOR
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID_DESENVOLVEDOR")]
    public partial class TB_DESENVOLVEDOR
    {
        /// <summary>
        /// Create a new TB_DESENVOLVEDOR object.
        /// </summary>
        /// <param name="iD_DESENVOLVEDOR">Initial value of ID_DESENVOLVEDOR.</param>
        /// <param name="nM_DESENVOLVEDOR">Initial value of NM_DESENVOLVEDOR.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TB_DESENVOLVEDOR CreateTB_DESENVOLVEDOR(short iD_DESENVOLVEDOR, string nM_DESENVOLVEDOR)
        {
            TB_DESENVOLVEDOR tB_DESENVOLVEDOR = new TB_DESENVOLVEDOR();
            tB_DESENVOLVEDOR.ID_DESENVOLVEDOR = iD_DESENVOLVEDOR;
            tB_DESENVOLVEDOR.NM_DESENVOLVEDOR = nM_DESENVOLVEDOR;
            return tB_DESENVOLVEDOR;
        }
        /// <summary>
        /// There are no comments for Property ID_DESENVOLVEDOR in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short ID_DESENVOLVEDOR
        {
            get
            {
                return this._ID_DESENVOLVEDOR;
            }
            set
            {
                this.OnID_DESENVOLVEDORChanging(value);
                this._ID_DESENVOLVEDOR = value;
                this.OnID_DESENVOLVEDORChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _ID_DESENVOLVEDOR;
        partial void OnID_DESENVOLVEDORChanging(short value);
        partial void OnID_DESENVOLVEDORChanged();
        /// <summary>
        /// There are no comments for Property NM_DESENVOLVEDOR in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NM_DESENVOLVEDOR
        {
            get
            {
                return this._NM_DESENVOLVEDOR;
            }
            set
            {
                this.OnNM_DESENVOLVEDORChanging(value);
                this._NM_DESENVOLVEDOR = value;
                this.OnNM_DESENVOLVEDORChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NM_DESENVOLVEDOR;
        partial void OnNM_DESENVOLVEDORChanging(string value);
        partial void OnNM_DESENVOLVEDORChanged();
    }
    /// <summary>
    /// There are no comments for CURSOModel.TB_LINGUAGEM in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID_LINGUAGEM
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID_LINGUAGEM")]
    public partial class TB_LINGUAGEM
    {
        /// <summary>
        /// Create a new TB_LINGUAGEM object.
        /// </summary>
        /// <param name="iD_LINGUAGEM">Initial value of ID_LINGUAGEM.</param>
        /// <param name="nM_LINGUAGEM">Initial value of NM_LINGUAGEM.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TB_LINGUAGEM CreateTB_LINGUAGEM(int iD_LINGUAGEM, string nM_LINGUAGEM)
        {
            TB_LINGUAGEM tB_LINGUAGEM = new TB_LINGUAGEM();
            tB_LINGUAGEM.ID_LINGUAGEM = iD_LINGUAGEM;
            tB_LINGUAGEM.NM_LINGUAGEM = nM_LINGUAGEM;
            return tB_LINGUAGEM;
        }
        /// <summary>
        /// There are no comments for Property ID_LINGUAGEM in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID_LINGUAGEM
        {
            get
            {
                return this._ID_LINGUAGEM;
            }
            set
            {
                this.OnID_LINGUAGEMChanging(value);
                this._ID_LINGUAGEM = value;
                this.OnID_LINGUAGEMChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID_LINGUAGEM;
        partial void OnID_LINGUAGEMChanging(int value);
        partial void OnID_LINGUAGEMChanged();
        /// <summary>
        /// There are no comments for Property NM_LINGUAGEM in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NM_LINGUAGEM
        {
            get
            {
                return this._NM_LINGUAGEM;
            }
            set
            {
                this.OnNM_LINGUAGEMChanging(value);
                this._NM_LINGUAGEM = value;
                this.OnNM_LINGUAGEMChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NM_LINGUAGEM;
        partial void OnNM_LINGUAGEMChanging(string value);
        partial void OnNM_LINGUAGEMChanged();
    }
}
